version: '3.5'

services:
    nginx-proxy:
        container_name: nginx_proxy
        image: jwilder/nginx-proxy:latest
        ports:
            - "80:80"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro

    php:
        container_name: apache_php
        depends_on:
            - db
        build:
            context: './.docker/php/'
        volumes:
            - ./.docker/php/000-default.conf:/etc/apache2/sites-available/000-default.conf
            - ./api/:/var/www/html/
        environment:
            - VIRTUAL_HOST=project.loc

    db:
        container_name: db
        image: mysql:5.7
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./.docker/mysql/setup.sql:/docker-entrypoint-initdb.d/setup.sql
            - ./.docker/mysql/db_data/:/var/lib/mysql/

    adminer:
        container_name: adminer
        image: adminer
        restart: always
        depends_on:
            - db
        environment:
            - VIRTUAL_HOST=adminer.loc
            
    redis:
        container_name: redis
        image: redis:alpine
        command: redis-server
        ports:
         - "6379:6379"
        volumes:
         - .redis/redis-data:/var/lib/redis
         - .redis/redis.conf:/usr/local/etc/redis/redis.conf
        environment:
         - REDIS_REPLICATION_MODE=master